// -----------------------------
// ARMORED CASTING FOR BARDS
// -----------------------------

DEFINE_ACTION_FUNCTION armored_bards BEGIN 

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5__yaras.d5~) BEGIN
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5__semi_armor.d5~) BEGIN

INCLUDE ~%MOD_FOLDER%/lib/d5_armored_casting.tpa~
LAM D5_ARMORED_CASTING

COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ ~override~
	PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
	  READ_SHORT 0x1c type
	  READ_LONG 0x22 appearance
	  PATCH_IF (type = 2) BEGIN // armor
		PATCH_IF (appearance = 16690) BEGIN // leather appearance
		  LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 177 parameter1 = 5 parameter2 = 5 timing = 2 STR_VAR resource = ~d5arca1~ END
		END
/*
		PATCH_IF (appearance = 16691) BEGIN // chain appearance
		  LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 177 parameter1 = 5 parameter2 = 5 timing = 2 STR_VAR resource = ~d5arca2~ END
		END
*/
/*
		PATCH_IF (appearance = 16692) BEGIN // plate appearance
		  LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 177 parameter1 = 5 parameter2 = 5 timing = 2 STR_VAR resource = ~d5arca3~ END
		END
*/
	  END
	END
BUT_ONLY

/* no need - IR already allows bards to cast in (all???) armor
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5brdir.spl~
  PATCH_FOR_EACH val IN ~1~ ~2~ BEGIN
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~ag#irs%val%~ END
  END
  PATCH_FOR_EACH val IN ~10~ ~15~ ~20~ ~30~ BEGIN
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~7c#ir%val%~ END
  END
*/
	
//Description update 
ACTION_GET_STRREF 9562 bard
OUTER_SPRINT old @11010
OUTER_SPRINT new @11020
OUTER_PATCH_SAVE bard ~%bard%~ BEGIN 
	REPLACE_TEXTUALLY ~%old%~ ~%new%~
END 
STRING_SET_EVALUATE 9562 ~%bard%~

END	//	end if no semi-casting
END	//	end if no YARAS

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5zblar.spl~) BEGIN
  COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5zblar.spl~
END

ACTION_IF (FILE_EXISTS_IN_GAME ~d5__semi_armor.d5~) BEGIN
  COPY_EXISTING ~d5zblar.spl~ ~override~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5zw172l~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5zarml~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5zarm1l~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5zarm2l~ END
  IF_EXISTS
END

ACTION_IF (FILE_EXISTS_IN_GAME ~d5__yaras.d5~) BEGIN
  COPY_EXISTING ~d5zblar.spl~ ~override~
    PATCH_FOR_EACH val IN ~1~ ~2~ ~3~ BEGIN
      LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5_cstp%val%~ END
    END
    PATCH_FOR_EACH val IN ~1~ ~2~ BEGIN
      LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5_cstm%val%~ END
      LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5_cstl%val%~ END
      LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5_cstd%val%~ END
    END
  IF_EXISTS
END

ACTION_IF (FILE_EXISTS_IN_GAME ~d5__semi_armor.d5~) OR (FILE_EXISTS_IN_GAME ~d5__yaras.d5~) BEGIN
 APPEND ~clabba01.2da~ ~BARD_CAST   AP_D5ZBLAR  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ UNLESS ~AP_D5ZBLAR~
 COPY_EXISTING ~kitlist.2da~ ~override~
  COUNT_2DA_COLS cols
  READ_2DA_ENTRIES_NOW ~r2en_kitlist~ 10
  FOR (row = 2; row < r2en_kitlist; row += 1) BEGIN
    READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 5 kit_table
    READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 8 class_num
    PATCH_IF (class_num = 5) BEGIN
      INNER_ACTION BEGIN
        ACTION_IF (FILE_EXISTS_IN_GAME ~%kit_table%.2da~) BEGIN
          APPEND ~%kit_table%.2da~ ~BARD_CAST   AP_D5ZBLAR  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ UNLESS ~AP_D5ZBLAR~
        END
      END
    END
  END
 BUT_ONLY
END

END 	//	end define function
//____________________________________________________________________________________
